# render.yaml
# This file defines your services on Render.com

services:
  # Web Service for your FastAPI Backend
  - type: web
    name: irrbb-backend
    env: python
    # A custom build command to ensure system dependencies are installed
    # This is an alternative to putting apt-get in Dockerfile if you prefer
    # Render's native build system. However, for full control, Dockerfile is better.
    # We'll stick to Dockerfile for this example, so this is commented out.
    # buildCommand: "pip install --no-cache-dir -r requirements.txt"
    # startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    
    # Use Docker for building and running the service
    dockerfilePath: Dockerfile
    
    # The command to run the service inside the Docker container
    # This will execute your start.sh script
    command: "./start.sh"
    
    # Environment variables for your application
    envVars:
      - key: DATABASE_URL
        # This value will be automatically populated by Render from the PostgreSQL service below
        # Make sure the database name matches what you set for POSTGRES_DB in the database service
        value: ${irrbb-postgres.internalConnectionString}?sslmode=disable
      - key: PYTHON_VERSION
        value: 3.10.12 # Specify Python version for consistency

    # Health check for your service (optional but good practice)
    healthCheckPath: /

  # PostgreSQL Database Service
  - type: pserv
    name: irrbb-postgres
    plan: free # Use 'free' for development, upgrade to 'starter' or 'pro' for production
    # Environment variables for the PostgreSQL database (matching your main.py)
    envVars:
      - key: POSTGRES_USER
        value: irrbb_user
      - key: POSTGRES_PASSWORD
        value: irrbb_password
      - key: POSTGRES_DB
        value: irrbb_db
